import { chromium } from 'playwright';
const EXE='/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const b=await chromium.launch({executablePath:EXE,args:['--use-gl=swiftshader','--enable-unsafe-swiftshader']});
const p=await b.newPage();
await p.goto('http://localhost:5173/?play',{waitUntil:'load'});
await p.waitForFunction(()=>window.__GAME_READY===true,{timeout:20000});
await p.evaluate(()=>window.__gotoRoom('court-tribunal'));
await p.waitForFunction(()=>window.__GAME_READY===true,{timeout:8000});
await p.waitForTimeout(2700);
console.log(JSON.stringify(await p.evaluate(()=>window.__arena()),null,1));
console.log('player:', JSON.stringify(await p.evaluate(()=>window.__ppos())));
await p.keyboard.down('ArrowLeft'); await p.waitForTimeout(2200); await p.keyboard.up('ArrowLeft');
console.log('after push west:', JSON.stringify(await p.evaluate(()=>window.__ppos())), '| seal should hold at ~2449');
await b.close();
